badge_ci:
  enabled: false
  settings:
    color: "purple"
    label: "Bitrise"
    logo: "bitrise"

badge_ticket:
  enabled: true
  settings:
    color: "black"
    label: "Github"
    sed_pattern: '.*\[GH-([0-9]+)\].*'
    url: "https://github.com/aiKrice/badgetizr/issues/%s"
    logo: "github"

badge_base_branch:
  enabled: true
  settings:
    color: "orange"
    label: "Base Branch"
    base_branch: "develop"

badge_wip:
  enabled: true
  settings:
    color: "yellow"
    label: "WIP"
    logo: "vlcmediaplayer"

badge_dynamic:
  enabled: true
  settings:
    patterns:
      - badge_1:
        pattern: "- [ ] Task 1"
        label: "Task 1"
        value: "Not done"
        color: "orange"
      - badge_2:
        pattern: "- [x] Task 2"
        label: "Task 2"
        value: "Done"
        color: "darkgreen"
